name: Deploy Heroku

on:
  push:
    branches: [development]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.0.0
        with:
          node-version: 14.x

      - name: Instalar dependencias
        run: yarn install

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0

      - name: Deploy to Heroku
        uses: AkhileshNS/heroku-deploy@v3.12.12
        with:
          # This will be used for authentication. You can find it in your heroku homepage account settings
          heroku_api_key: ${{secrets.HEROKU_TOKEN}}
          heroku_email: fjunior@gmail.com
          heroku_app_name: devin-orkut-graphql
  
      - name: Discord Message Notify
        uses: appleboy/discord-action@0.0.3
        with:
          webhook_id: ${{ secrets.WEBHOOK_ID }}
          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
          color: "#48f442"
          username: "Mr. Robot"
          message: ${{ github.event_name }} ${{ github.ref_name }} by ${{ github.actor }}.
      - name: Slack notification
        env:
            SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
            SLACK_USERNAME: ThisIsMyUsername # Optional. (defaults to webhook app)
            SLACK_CHANNEL: general # Optional. (defaults to webhook)
            SLACK_AVATAR: repository # Optional. can be (repository, sender, an URL) (defaults to webhook app avatar)
            SLACK_CUSTOM_PAYLOAD: '{"text":"A branch {{ GITHUB_REF_NAME }} recebeu um {{ GITHUB_EVENT_NAME }} de {{ GITHUB_ACTOR }}"}'
        uses: Ilshidur/action-slack@2.0.2
        with:
            args: 'A new commit has been pushed.' # Optional
